---
date_format: "%d/%b/%Y:%H:%M:%S %z"
pattern: !ruby/regexp '/^(\S*) (\S*) (\S*) (\[[^\]]+\]) (?-mix:"([^"\\]*(?:\\.[^"\\]*)*)") (\S*) (\S*) (?-mix:"([^"\\]*(?:\\.[^"\\]*)*)") (?-mix:"([^"\\]*(?:\\.[^"\\]*)*)")$/'
log_file_path: "./sample.log"
